### ISSUE TITLE
nefunguje odesílání

### ISSUE THREAD

**Issue by LukasLibich** [ingui-n/uhel-pohledu-order#5]
při odeslání formuláře z mobilu a z PC, se nezobrazí nic, jen prázdná stránka a formulář se neodešle.  To ani v případě, že se použije originální  soubor index.php (přejmenovaný na shop-index.php). Test nefunkční ani v doplněném html...  přikládám zip všech provedených změn [http://leteckaposta.cz/668525456](url)
Je tam celý ořezaný web s vloženým e-shopem, bude takto jak zveřejněn.

**Comment by LukasLibich** [comment]
Bohužel ani když se zadá heslo do configu, nejde odesílání...  Zobrazí se zpráva s chybou 500 a info že to stránka nedokáže zpracovat...  nemůžu míst špatně nainstalovaný composer nebo něco takového? php je verze 7.4.12

**Comment by e2221** [comment]
> Bohužel ani když se zadá heslo do configu, nejde odesílání... Zobrazí se zpráva s chybou 500 a info že to stránka nedokáže zpracovat... nemůžu míst špatně nainstalovaný composer nebo něco takového? php je verze 7.4.12

Pustil jsi ve složce, kde je composer.json příkaz composer update?

**Comment by ingui-n** [comment]
> při odeslání formuláře z mobilu a z PC, se nezobrazí nic, jen prázdná stránka a formulář se neodešle.
Soubor `composer.json` se musí nacházet v předchozím adresáři, stejně jako je tomu v [main branch](https://github.com/ingui-n/uhel-pohledu-order). Poté znovu proveďte příkaz `composer update`.

**Comment by LukasLibich** [comment]
už se posílá, chyba na mé straně, asi jsem přehlédl a spustil update v jiné složce. Už řeším jen zalamování... bohužel mám to na neveřejném serveru a nedokážu to teď pustit ven. Přikládám leteckou poštu sem
[web.zip](https://github.com/ingui-n/uhel-pohledu-order/files/5578577/web.zip)
ještě procházím poslední css pro zmińovaný kód ale zatím žádný z nalezených, který jsem zakomentoval neřeší problém... :( nicméně to už bude asi čistě můj problém.

**Comment by ingui-n** [comment]
Prosím o použití nejnovější verze [v1.0.2](https://github.com/ingui-n/uhel-pohledu-order/releases/tag/v1.0.2). Vše by tam mělo fungovat jak má 👍🏾
