### ISSUE TITLE
Tlačítko Odeslat objednávku 

### ISSUE THREAD

**Issue by LukasLibich** [ingui-n/uhel-pohledu-order#6]
Z nějakého důvodu se zobrazuje špatně. 

Předpokládám že jde o problém -konflikt CSS, tak jsem zanechal až na konec. Ještě jsem neřešil ani po své linii. To spíš kdyby vás něco napadlo. :)

**Comment by e2221** [comment]
Jediný, co mě teď napadá - zobraz si zdrojový kód stránky v prohlížeči a zkuse se proklinout do css souborů, zda ti je to načte, možná bude spíš jen špatná cesta k css.
Je možnost to vidět na nějaké url?

**Comment by ingui-n** [comment]
Ano, jednalo se konflikt CSS. Konkrétně z includovaných knihoven, nacházelo se tam `word-wrap: break-word;`.
Odkaz na nový release: https://github.com/ingui-n/uhel-pohledu-order/releases/tag/v1.0.1
