### ISSUE TITLE
Pocitani ceny - mobilni zarizeni

### ISSUE THREAD

**Issue by LukasLibich** [ingui-n/uhel-pohledu-order#7]
Kuci problem, na iphone jsem zjistil ze se nepocita cena.. testovane prohlizece safari a chrome. Formular se odesle a kontroluje hodnoty standartne.

**Comment by ingui-n** [comment]
Mohu poprosit o report verzí obou zmíněných prohlížečů?

**Comment by LukasLibich** [comment]
> Mohu poprosit o report verzí obou zmíněných prohlížečů?

Bohužel u safari se nepodarilo najit verzi, nejde to ani na dnes instalovane verzi iOS 14.2 pro iPhone11. ![image](https://user-images.githubusercontent.com/74828540/99989401-e0919d00-2db2-11eb-98e1-84bcd7a6971e.png) tohle je des updatovany chrome ktery ma stejny problem jako pred update

**Comment by ingui-n** [comment]
Dobrý den, protože nemám přístup k žádnému iPhonu, tak jsem provedl test pouze v emulovaném režimu. Vypočítání ceny opravdu na žádném prohlížeči nefungovalo, tak jsem si zkusil stránku otestovat i na své doméně. Tam vše fungovalo, takže si myslím, že chyba bude v implementování formuláře (a scriptu) na vaši stránku. Nedošlo totiž k načtení ničeho ze souboru [script.js](https://github.com/ingui-n/uhel-pohledu-order/blob/main/html/scripts/script.js). Zkusil jsem ho tedy upravit. Snad bude již fungovat v nové [verzi](https://github.com/ingui-n/uhel-pohledu-order/releases/tag/v1.0.3).

**Comment by LukasLibich** [comment]
Nová verze (opravené soubory) nasazeny. Restartováno, vymazaná historie ale bohužel problém setrvává. Dokonce testováno na safari Iphone SE2 (2020) - první zobrazení stránky ( takže nedotčeno cash a pod) a stále stejný problém. ...

**Comment by LukasLibich** [comment]
> Nová verze (opravené soubory) nasazeny. Restartováno, vymazaná historie ale bohužel problém setrvává. Dokonce testováno na safari Iphone SE2 (2020) - první zobrazení stránky ( takže nedotčeno cash a pod) a stále stejný problém. ... resp. ani se nezobrazí počáteční cena. Je dost možné, že se nespouští stále script, jelikož se neprovádí ani kontrola obsahu formuláře - např. číslo popisné..
Napadá mně, jestli není konflikt přímo s zbytkem stránky, v níž je umístěn shop... přístup na server byl předán Lukášovi :)
Otestuji ještě kopii bez "obálky" webu.

Takže ano, bez webu okolo to běží... tedy jdu hledat k sobě možný konflikt

**Comment by LukasLibich** [comment]
hotovo funkční, sorry za zmatky...
