### ISSUE TITLE
Mailova zprava

### ISSUE THREAD

**Issue by LukasLibich** [ingui-n/uhel-pohledu-order#8]
Zprava v mailu neobsahuje pocet objednanych ks 😆 musel jsem jich videt nekolik abych si vsiml🙈😉

**Comment by ingui-n** [comment]
Do emailu byla přidána položka s počtem objednaných kusů. Použijte prosím nejnovější [verzi](https://github.com/ingui-n/uhel-pohledu-order/releases/tag/v1.0.3).

**Comment by LukasLibich** [comment]
opravene soubory implementovany, server restartovan a testovaci objednavka zaslana, čekám na potvrzení :)

**Comment by LukasLibich** [comment]
Uzaviram ticket, problem vyresen, potvrzeni prijato
